name: CICD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create application.properties
        run: |
          echo "${{ secrets.APPLICATION_YAML }}" > src/main/resources/application.yaml

      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-jar
          path: build/libs/$PROJECT_JAR_NAME.jar

      - name: Upload Docker file
        uses: actions/upload-artifact@v4
        with:
          name: my-dockerfile
          path: Dockerfile
          
  integration:
    needs: build
    runs-on: [ ubuntu-latest ]
    env:
      DOCKER_IMAGE_NAME: raccoon
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: my-jar
          path: build/libs/

      - name: Download Dockerfile artifact
        uses: actions/download-artifact@v4
        with:
          name: my-dockerfile
          path: .

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:latest .
          docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:latest
  deploy:
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop $DOCKER_IMAGE_NAME || true
            docker rm $DOCKER_IMAGE_NAME || true
            docker pull $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:latest
            docker run -d -p 8080:8080 --name springboot-app $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:latest
